dashboard:
    path: /
    controller: App\Controller\DashboardController::index

clientes:
    path: /clientes
    controller: App\Controller\ClientesController::index

clientes_create:
    path: /clientes/create
    controller: App\Controller\ClientesController::create
